{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators"]]},"identifier":{"url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorErrorHandler","interfaceLanguage":"swift"},"metadata":{"symbolKind":"typealias","role":"symbol","externalID":"s:14SwiftOperators20OperatorErrorHandlera","modules":[{"name":"SwiftOperators"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"OperatorErrorHandler"}],"title":"OperatorErrorHandler","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OperatorErrorHandler"}]},"sections":[],"abstract":[{"text":"A function that receives an operator precedence error and may do with it","type":"text"},{"type":"text","text":" "},{"text":"whatever it likes.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OperatorErrorHandler"},{"kind":"text","text":" = ("},{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorError","kind":"typeIdentifier","preciseIdentifier":"s:14SwiftOperators13OperatorErrorO","text":"OperatorError"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Operator precedence error handlers are passed into each function in the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"operator-precedence parser that can produce a failure. The handler"},{"type":"text","text":" "},{"type":"text","text":"may choose to throw (in which case the error will propagate outward) or"},{"type":"text","text":" "},{"text":"may separately record\/drop the error and return without throwing (in","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which case the operator-precedence parser will recover)."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftoperators\/operatorerrorhandler"]}],"references":{"doc://com.SwiftyLab.HelperCoders/documentation/SwiftOperators/OperatorErrorHandler":{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorErrorHandler","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"OperatorErrorHandler","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OperatorErrorHandler"}],"kind":"symbol","abstract":[{"type":"text","text":"A function that receives an operator precedence error and may do with it"},{"text":" ","type":"text"},{"text":"whatever it likes.","type":"text"}],"type":"topic","title":"OperatorErrorHandler","url":"\/documentation\/swiftoperators\/operatorerrorhandler"},"doc://com.SwiftyLab.HelperCoders/documentation/SwiftOperators/OperatorError":{"navigatorTitle":[{"text":"OperatorError","kind":"identifier"}],"title":"OperatorError","type":"topic","url":"\/documentation\/swiftoperators\/operatorerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OperatorError"}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorError","abstract":[{"text":"Describes errors that can occur when working with user-defined operators.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/SwiftOperators":{"url":"\/documentation\/swiftoperators","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators","kind":"symbol","type":"topic","title":"SwiftOperators","role":"collection","abstract":[]}}}